semuxproject/semux-core

- docs/Block-Rewards.md
- docs/Message-Encoding.md
- docs/Network-Protocol.md
- docs/README.md
- docs/RESTful-API.md
- docs/Semux-BFT-Consensus.md
Start to fill int network protocol documentation.
There's more to fill in certainly, but a start.
Also some minor updates for clarity to other docs.
> Docs: Start filling in network protocol.

- src/main/java/org/semux/util/TimeUtil.java
Add retry loop for flakey servers
> Net: Retry NTP lookup

- src/main/java/org/semux/gui/SwingUtil.java
- src/main/java/org/semux/gui/panel/TransactionsPanel.java
Also fix bad logic in selecting previously selected.
> GUI: Use address book for address alias

- src/main/java/org/semux/net/msg/MessageQueue.java
for debugging, useful to have network trace time stats
> Net: Trace logging for message times

- pom.xml
Needs validation but should fix problem with certain
folder naming.
fixes #24
> Tools: fix windows unicode directories

- src/main/java/org/semux/net/SemuxMessageHandler.java
- src/main/java/org/semux/net/msg/MessageFactory.java
- src/test/java/org/semux/net/msg/MessageFactoryTest.java
This enables adding of new messages without breaking backward compatibility.
> P2P: allow unknown message type

- docs/Block-Rewards.md
Updated Real-time API as clickable url
> Docs: update Real-time API url

- pom.xml
- src/main/java/org/semux/api/http/HttpHandler.java
update libs for OSHI, swagger, jackson, etc.
OSHI update is probably most important as users have been experiencing
issues with versions of windows causing errors.
Will submit separate change to add error handling around it as well.
> Util: Update libs

- src/main/java/org/semux/cli/SemuxCli.java
- src/main/java/org/semux/gui/SemuxGui.java
if there is no password, no sense in asking user to enter it.
Fixes #107
> GUI: Check for empty pass before prompting pass

- src/main/java/org/semux/consensus/SemuxBft.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/TransactionResult.java
Fixes #110 
This should fix chain hanging, but hard to test with devnet.
> VM: Handle failed transactions to just eat all gas.

- src/main/java/org/semux/gui/dialog/ConsoleDialog.java
allow both 'null' and leaving optional fields off the end.
> GUI: Add support for nullable parameters in console

- src/main/java/org/semux/gui/dialog/RecoverHdWalletDialog.java
- src/main/resources/org/semux/gui/messages.properties
We just import the wallet addresses, but do not replace the existing seed
If user wants to replace seed, they can start a wallet from scratch
Fixes #105
> GUI: Wallet import/recover of HD keys does not replace existing seed

- src/main/java/org/semux/JvmOptions.java
> Tools: suppress outputs from Log4J2 in JvmOptions

- README.md
> Docs: Update readme suggesting openJDK

- config/semux.properties
will tune this down post acceptance and tuning.
> Config: update default block gas limit for testnet RC3

- src/main/java/org/semux/core/bip39/MnemonicGenerator.java
- src/test/java/org/semux/core/bip39/MnemonicGeneratorTest.java
- src/test/java/org/semux/core/bip39/Vector.java
- src/test/java/org/semux/core/bip39/VectorReader.java
- src/test/java/org/semux/core/bip39/VectorTest.java
- src/test/resources/vector/vector.json
Use NFKD encoding to ensure that japanese spaces work even
with using english pass phrases.
> Core: Fix HD phrase generation/validation with japanese

- config/semux.properties
- pom.xml
- src/main/java/org/semux/cli/SemuxCli.java
- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/config/Config.java
- src/main/java/org/semux/config/Constants.java
- src/main/java/org/semux/config/DevnetConfig.java
- src/main/java/org/semux/config/MainnetConfig.java
- src/main/java/org/semux/config/TestnetConfig.java
- src/main/java/org/semux/consensus/SemuxBft.java
- src/main/java/org/semux/consensus/SemuxSync.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/core/PendingManager.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/Wallet.java
- src/main/java/org/semux/gui/SemuxGui.java
- src/main/java/org/semux/gui/panel/ReceivePanel.java
- src/test/java/org/semux/cli/SemuxCliTest.java
- src/test/java/org/semux/core/CorePerformanceTest.java
- src/test/java/org/semux/core/TransactionExecutorTest.java
- src/test/java/org/semux/core/VmTest.java
- src/test/java/org/semux/rules/KernelRule.java
- Disable VM fork signaling on main net;
- Disable HD wallet before we make it compatible with Ledger bip32-ed25519.
> Disable features in preparation of v1.4.0

- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/TransactionResult.java
- src/main/resources/org/semux/api/swagger/v2.2.0.json
- src/test/java/org/semux/api/v2/SemuxApiTest.java
- src/test/java/org/semux/integration/TransactTest.java
- Remove the block and gas info from the TransactionType and BlockType
> Refactor VM-related API endpoints

- docs/Block-Explorers.md
- docs/Block-Rewards.md
- docs/Delegates-and-Validators.md
In the website we state that Semux is a blockchain platform. 
In docs we say 'New Semux created every block' (new blockchain platform created every block?)
Here is my proposal to distinguish these two terms: 
Semux is a blockchain platform. 
**SEM** is a native cryptocurrency of Semux platform. 
Thus I added some minor fixes to docs and more descriptions.
> Docs: update terminology 

- src/main/java/org/semux/consensus/SemuxSync.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/net/SemuxP2pHandler.java
- src/main/java/org/semux/net/msg/consensus/BlockPartsMessage.java
This PR intends to finish the incomplete block parts feature.
> Net: implement the missing BLOCK_PARTS handlers

- src/main/java/org/semux/config/TestnetConfig.java
- src/main/java/org/semux/consensus/SemuxSync.java
Please accept prior to reboot testnet.  It will break if run against current testnet.
> Concensus: update max testnet validator check for testnet reboot

- src/main/java/org/semux/api/util/TransactionBuilder.java
- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/config/Config.java
- src/main/java/org/semux/consensus/SemuxBft.java
- src/main/java/org/semux/core/Amount.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/core/PendingManager.java
- src/main/java/org/semux/core/Transaction.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/TransactionResult.java
- src/main/java/org/semux/vm/client/SemuxInternalTransaction.java
- src/test/java/org/semux/core/TransactionResultTest.java
- src/test/java/org/semux/core/VmTest.java
- src/test/java/org/semux/vm/client/InternalTransactionTest.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
- src/test/java/org/semux/vm/client/VmTransactionTest.java
> VM: resolve issue #187

- src/main/java/org/semux/gui/dialog/ConsoleDialog.java
- src/main/java/org/semux/util/CommandParser.java
- src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
- src/test/java/org/semux/util/CommandParserTest.java
Tested with quotes and escaped quotes.
Fixes #13
> GUI: Allow quotes in console dialog

- src/main/java/org/semux/config/DevnetConfig.java
- src/main/java/org/semux/gui/dialog/ConsoleDialog.java
- src/main/java/org/semux/gui/dialog/TransactionDialog.java
- src/main/java/org/semux/gui/panel/TransactionsPanelFilter.java
- src/main/resources/org/semux/gui/messages.properties
- src/test/java/org/semux/consensus/SemuxSyncTest.java
- src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
- src/test/java/org/semux/util/CommandParserTest.java
> GUI: display gas price in transaction dialog

- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/java/org/semux/config/DevnetConfig.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/gui/dialog/ConsoleDialog.java
- src/main/java/org/semux/gui/dialog/TransactionDialog.java
- src/main/java/org/semux/gui/panel/TransactionsPanelFilter.java
- src/main/java/org/semux/net/Peer.java
- src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java
- src/main/resources/org/semux/gui/messages.properties
- src/test/java/org/semux/consensus/SemuxSyncTest.java
- src/test/java/org/semux/gui/dialog/ConsoleDialogTest.java
- src/test/java/org/semux/util/CommandParserTest.java
>  Core: stop signaling fork after activation

- pom.xml
- src/main/java/org/semux/api/http/HttpHandler.java
- src/main/java/org/semux/api/util/TransactionBuilder.java
- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/core/Transaction.java
- src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java
- src/main/resources/org/semux/api/swagger/v2.3.0.json
- src/test/java/org/semux/api/util/TransactionBuilderTest.java
- src/test/java/org/semux/api/v2/SemuxApiTest.java
- Added support for EVM Constenople features;
- Enhance API interfaces;
- Change the P2P capability set.
Close #199 and close #201
> VM, API and P2P updates

- pom.xml
- src/main/java/org/semux/api/http/HttpHandler.java
Pre-release, seems good to update things to latest version.
> Core: Update libs to latest version

- src/main/java/org/semux/api/util/TransactionBuilder.java
- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/net/NodeManager.java
- src/main/java/org/semux/net/msg/MessageQueue.java
- src/test/java/org/semux/bench/VMPerformance.java
- src/test/java/org/semux/consensus/VoteSetTest.java
- src/test/java/org/semux/vm/client/InternalTransactionTest.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
- src/test/java/org/semux/vm/client/VmTransactionTest.java
Fix to use some new java features, and simplify
Fix some error handling for Enums
> Trivial: Minor fixes

- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/resources/org/semux/api/swagger/v2.3.0.json
- src/test/java/org/semux/api/v2/SemuxApiTest.java
> API: show gas and gasPrice in transaction response

- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/config/Config.java
- src/main/java/org/semux/consensus/SemuxSync.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/core/BlockPart.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/net/SemuxP2pHandler.java
It's optional and disabled by default. Only works with the `testnet` currently.
> Sync: add sync.skipVotes option

- config/semux.properties
- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/config/Config.java
- src/main/java/org/semux/consensus/SemuxSync.java
- src/test/java/org/semux/consensus/SemuxSyncTest.java
To speed up the syncing process by skipping votes for non-pivot blocks.
YES
Manually tested with both mainnet and testnet
N/A
> Sync: enable fast_sync protocol

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Simplify the issue/PR templates
> Docs: update github issue templates

- src/main/java/org/semux/Launcher.java
- src/main/java/org/semux/cli/SemuxCli.java
- src/main/java/org/semux/cli/SemuxOption.java
- src/main/java/org/semux/gui/SemuxGui.java
- src/main/java/org/semux/gui/dialog/InitializeHdWalletDialog.java
- src/main/java/org/semux/gui/panel/ReceivePanel.java
- src/main/resources/org/semux/cli/messages.properties
- src/main/resources/org/semux/gui/messages.properties
- src/test/java/org/semux/cli/SemuxCliTest.java
To allow users to turn on/off HD wallet based on their needs.
YES
Existing unit tests
N/A
> GUI, CLI: add --hdwallet option

- src/main/java/org/semux/api/http/HttpChannelInitializer.java
- src/main/java/org/semux/api/http/HttpConstants.java
- src/main/java/org/semux/api/http/HttpHandler.java
To allow longer parameters in URL and increase header size limit.
Existing unit tests
#236
> API: increase HTTP url, header, chunk sizes

- src/main/java/org/semux/gui/panel/HomePanel.java
Fixes #220
Adds create/call to home panel
Existing functionality
fixes #220
> Add create/call to home panel

- config/semux.properties
- src/main/java/org/semux/gui/dialog/TransactionDialog.java
- src/main/java/org/semux/gui/dialog/TransactionResultDialog.java
- src/test/java/org/semux/bench/SemuxPerformance.java
Enhance the bench tool to support `CALL`
Manually tested it.
N/A
> Tools: send CALL transactions through the bench tool

- src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java
Add getVote and getVotes contracts that delegate to existing methods to expose them via VM calls.
Manual tests, though we should figure out a way to test all the other precompiled contracts we have
Fixes #244
> VM: Add getVote/getVotes precompiled contracts

- src/main/java/org/semux/api/v2/SemuxApiImpl.java
To resolve an issue with local call or gas estimation.
Existing tests
Issue-#257
> API: fix local call/estimate gas issue, #257

- src/main/java/org/semux/cli/SemuxCli.java
- src/main/java/org/semux/cli/SemuxOption.java
- src/main/java/org/semux/core/ActivatedForks.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/util/SystemUtil.java
- src/main/resources/org/semux/cli/messages.properties
Add the `--reindex` option to allow users to re-index the database to correct the state db.
Manually tested
N/A
> CLI: add reindex option

- pom.xml
- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/cli/SemuxCli.java
- src/main/java/org/semux/consensus/SemuxBft.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/TransactionResult.java
- src/main/java/org/semux/net/msg/MessageQueue.java
- src/main/java/org/semux/tools/DatabaseIntegrityChecker.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
- src/test/java/org/semux/vm/client/VmTransactionTest.java
- Applied a newer version of vm, which solves issue #260 and #249;
- Added a database integrity check tool;
- Update the database re-indexer.
Existing tests and newly added tests are all passing.
#260, #249
> VM: adopt new implementation

- pom.xml
- src/main/java/org/semux/api/ApiHandlerImpl.java
- src/main/java/org/semux/api/ApiVersion.java
- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/java/org/semux/core/Blockchain.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/core/TransactionResult.java
- src/main/java/org/semux/vm/client/SemuxInternalTransaction.java
- src/main/resources/org/semux/api/swagger/v2.4.0.json
- src/test/java/org/semux/api/v2/SemuxApiTest.java
- src/test/java/org/semux/core/BlockchainImplTest.java
- src/test/java/org/semux/core/TransactionResultTest.java
Add API endpoints for account code and storage
- `/account/code`
- `/account/storage`
Added new tests for the added feature
#263
> API: add code and storage query apis

- pom.xml
- src/main/java/org/semux/api/v2/TypeFactory.java
- src/main/java/org/semux/vm/client/SemuxInternalTransaction.java
- src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java
- src/test/java/org/semux/api/http/HttpHandlerTest.java
- src/test/java/org/semux/api/v2/SemuxApiTest.java
- src/test/java/org/semux/core/BlockchainImplTest.java
- src/test/java/org/semux/core/TransactionResultTest.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
Add internal transaction for vote/unvote from precompiled contracts.
Existing unit tests.
#249
> VM: add internal transaction for vote/unvote

- CHANGELOG.md
- src/main/java/org/semux/Kernel.java
- src/main/java/org/semux/api/v2/SemuxApiImpl.java
- src/main/java/org/semux/config/AbstractConfig.java
- src/main/java/org/semux/config/ChainSpec.java
- src/main/java/org/semux/config/Config.java
- src/main/java/org/semux/config/DevnetConfig.java
- src/main/java/org/semux/config/MainnetConfig.java
- src/main/java/org/semux/config/TestnetConfig.java
- src/main/java/org/semux/consensus/SemuxBft.java
- src/main/java/org/semux/core/ActivatedForks.java
- src/main/java/org/semux/core/Block.java
- src/main/java/org/semux/core/Blockchain.java
- src/main/java/org/semux/core/BlockchainImpl.java
- src/main/java/org/semux/core/Fork.java
- src/main/java/org/semux/core/ForkSignalSet.java
- src/main/java/org/semux/core/PendingManager.java
- src/main/java/org/semux/core/TransactionExecutor.java
- src/main/java/org/semux/util/TimeUtil.java
- src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java
- src/test/java/org/semux/core/BlockchainImplTest.java
- src/test/java/org/semux/core/CorePerformanceTest.java
- src/test/java/org/semux/core/TransactionExecutorTest.java
- src/test/java/org/semux/integration/UniformDistForkSyncingTest.java
- src/test/java/org/semux/vm/client/InternalTransactionTest.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
- src/test/java/org/semux/vm/client/VmTransactionTest.java
Add fork logic to ensure the network upgrading goes smoothly. 
Added new unit tests
N/A
> Core: add VOTING_PRECOMPILED_UPGRADE fork

- .github/CONTRIBUTING.md
- LICENSE
- misc/license_header.txt
Update license headers for current year
None
None
> Tools: Update license header templates

- README.md
- src/main/java/org/semux/config/DevnetConfig.java
- src/test/java/org/semux/bench/BlockchainPerformance.java
- src/test/java/org/semux/bench/SemuxPerformance.java
- src/test/java/org/semux/bench/VMPerformance.java
- src/test/java/org/semux/config/UnitTestnetConfig.java
- src/test/java/org/semux/core/BlockTest.java
- src/test/java/org/semux/core/BlockchainImplTest.java
- src/test/java/org/semux/core/CorePerformanceTest.java
- src/test/java/org/semux/core/TransactionExecutorTest.java
- src/test/java/org/semux/core/TransactionTest.java
- src/test/java/org/semux/core/state/AccountStateTest.java
- src/test/java/org/semux/core/state/DelegateStateTest.java
- src/test/java/org/semux/net/msg/p2p/handshake/v1/HelloMessageTest.java
- src/test/java/org/semux/net/msg/p2p/handshake/v1/WorldMessageTest.java
- src/test/java/org/semux/net/msg/p2p/handshake/v2/HelloMessageTest.java
- src/test/java/org/semux/net/msg/p2p/handshake/v2/WorldMessageTest.java
- src/test/java/org/semux/rules/KernelRule.java
- src/test/java/org/semux/vm/client/InternalTransactionTest.java
- src/test/java/org/semux/vm/client/PrecompiledContractTest.java
- src/test/java/org/semux/vm/client/VmTransactionTest.java
About 5 second blocks for devnet, and all forks activated.
Fixes #276
> Test: Devnet has forks activated and fast blocks
