semuxproject/semux-core

src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/core/Block.java
Log the reason for a block header being invalid.  As we recently found
the time issue for headers, it seems like we need clearer language for
logging failed vote reasons.
=> Consensus: More verbose logging for header validation

src/main/java/org/semux/gui/panel/SendPanel.java
Re-fix the account panel so send panel to/from are in same order
as account list, for users that do not name their accounts.
=>  GUI: Fix account list ordering in send panel

src/main/java/org/semux/api/v2/SemuxApiImpl.java, src/main/java/org/semux/api/v2/TypeFactory.java, src/main/resources/org/semux/api/swagger/v2.2.0.json, src/test/java/org/semux/api/v2/SemuxApiTest.java, src/test/java/org/semux/integration/TransactTest.java
If you request an individual transaction, we'll return the full object with transactionResult included.
if you are retrieving a block, we just leave it as a simple transaction without results as before.  We can change this in the future, but seems preferrable to prefer lighter weight calls unless necessary.
Also add gas information (gas, gasPrice, gasUsed) so that blockchain explorers can accurately show this along with calculating out actual fee (gasUsed*gasPrice)
=> API: Transaction result included in getTransaction

src/main/java/org/semux/cli/SemuxCli.java
we exit with correct exit code, but give user correct error.
fixes #93
=> CLI: Log bad password on exit.

src/main/java/org/semux/core/Wallet.java, src/main/java/org/semux/gui/panel/ReceivePanel.java, src/main/resources/org/semux/gui/messages.properties
The derivation path in full was confusing, and too much useless information
Use a concise form of it for aliases in wallet (localized)
Also give slightly more default width to account alias column, so it does not get truncated.
fixes #95
=> GUI: Make default alias for HD wallets more user friendly

src/main/java/org/semux/api/util/TransactionBuilder.java, src/main/java/org/semux/api/v2/SemuxApiImpl.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/core/Amount.java, src/main/java/org/semux/core/TransactionExecutor.java, src/main/resources/org/semux/api/swagger/v2.2.0.json, src/test/java/org/semux/core/VmTest.java
Update API to reflect
Fixes #100
=> VM: Remove fee for VM calls

src/main/java/org/semux/config/TestnetConfig.java, src/main/java/org/semux/consensus/SemuxBft.java
Testnet keeps dying because of dead validators.
Let's limit the number of validators to 15 such that we can
vote up alive validators to keep testnet healthy.
As testnet is already hung, do not need hardfork for this.
=> Core: Testnet uses max 15 validators

pom.xml, src/main/java/org/semux/api/v2/TypeFactory.java, src/main/java/org/semux/config/Constants.java, src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/consensus/SemuxSync.java, src/main/java/org/semux/consensus/VoteSet.java, src/main/java/org/semux/core/TransactionExecutor.java, src/main/resources/org/semux/api/swagger/v2.2.0.json
fix client sync, and add check to ensure that bad block is not
accepted on sync for testnet.
=> [WIP] RC3 - Raise gas limits & fix client sync

src/main/java/org/semux/consensus/VoteSet.java
Maybe @cryptokat can clarify, but doing a round here for initial blocks
(2 validators), will allow for both to propose and accept disparate
blocks.
I'm not sure case where round was necessary over ceil, if that is the case
we can just add a check where validators == 2 to fix.
Note: merging this into RC3 then down to various PRs will fix CI that is failing.
=> Core: Revert to using ceil for 2/3 vote

src/main/java/org/semux/consensus/SemuxBft.java
In order to have full decentralization, we cannot require that the
very first validators (semux1-4) are required for syncing.
Also in order to scale past a certain level, the validators cannot be
connected to from every client.
Currently, if semux1-4 go down (Even though they are no longer valiators)
clients are unable to sync from block 0.
This change allows for choosing to sync height based on active peers
if UR validators are unable to be found.
Fixes #73
=> Core: if original validators are unable to connect, do not deny sync

src/main/java/org/semux/core/BlockchainImpl.java
Prior forks would stop sycning at point of activation,
but with VM, it will only stop working when a new CREATE
or CALL type is used.
Keep signalling VM until activation deadline or such a point
we remove this check in future release.
fixes #106
=> Concensus: Keep signalling VM fork past acceptance.

src/main/java/org/semux/consensus/SemuxBft.java, src/main/java/org/semux/consensus/SemuxSync.java, src/test/java/org/semux/consensus/SemuxBftOnNewHeightTest.java, src/test/java/org/semux/consensus/VoteSetTest.java
- Quorum size `q` needs to be ceil of the `2 / 3 * n`. Take the syncing for example, we're picking a target height such that at least `q` number of nodes have reached that height;
- Revert the view check fix.
=> Consensus: fix the quorum size

src/main/java/org/semux/core/Block.java, src/main/java/org/semux/net/SemuxP2pHandler.java, src/main/java/org/semux/net/msg/MessageCode.java, src/main/java/org/semux/net/msg/MessageFactory.java, src/main/java/org/semux/net/msg/consensus/BlockPartsMessage.java, src/main/java/org/semux/net/msg/consensus/GetBlockPartsMessage.java
I'd propose to add two message types to support light clients. 
- `GET_BLOCK_PARTS` - block parts (header, transaction, receipts, votes) request
- `BLOCK_PARTS` - block parts response
In the short-term, we can use these protocols to speed up the syncing  by not requesting block votes.
=> Add GET_BLOCK_PARTS message

src/main/java/org/semux/config/AbstractConfig.java, src/test/java/org/semux/config/MainnetConfigTest.java
See the proposal at https://github.com/semuxproject/RFPs/blob/master/proposals/002/honeycrypto.md
=> Consensus: change the block rewards

src/main/java/org/semux/api/v2/TypeFactory.java, src/main/resources/org/semux/api/swagger/v2.2.0.json
Note: this exposes existing bug #187
=> API: Add internal transactions to API

src/main/java/org/semux/util/SimpleApiClient.java
It's useful for when running tests to get the response string to see
why a call failed, so read from error stream and log it.
=> Test: Update SimpleApiClient to check error stream.

src/main/java/org/semux/core/PendingManager.java
Need to get expected nonce from pending manager, not from stored chain,
as other transactions could have already update nonce for this block.
Fixes #200
=> Core: Fix pending manager nonce check.

src/main/java/org/semux/gui/SwingUtil.java, src/test/java/org/semux/api/http/HttpHandlerTest.java, src/test/java/org/semux/core/WalletTest.java, src/test/java/org/semux/integration/SyncingTest.java, src/test/java/org/semux/integration/TransactTest.java, src/test/java/org/semux/util/IOUtilTest.java
When running `mvn clean install` these newlines get added.
It gets old removing these files from commits.  If there's a suggestion
on how to get them consistent between devs, I'm all ears.
=> Trivial: formatting newlines for static imports

src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/core/Transaction.java, src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java, src/main/java/org/semux/vm/client/SemuxSpec.java, src/test/java/org/semux/vm/client/VmTransactionTest.java
=> Fix issue #212

src/main/java/org/semux/api/v2/SemuxApiImpl.java, src/main/java/org/semux/vm/client/SemuxPrecompiledContracts.java, src/main/resources/org/semux/api/swagger/v2.3.0.json
Still need to add unit tests.
Definitely open to renaming if another name fits better.  Naming is hard.
Fixes #196
=> API: Add call-local

src/main/java/org/semux/config/AbstractConfig.java
As mentioned in bug, current mainnet has blocks up to around 5600 TXs from perf tests.
Since standard transfers cost 5,000, we set 6,000 limit, so max block gas would be 30mil to be able to sync and maintain parity with old mainnet.
Note: Currently validators will only propose up to 10mil by default configuration, but at least they'll be able to sync.  Going with 10 million for first version of VM seems appropriate for default maxes to keep validator from being overwhelmed.
tested via bug, as well as able to get 9999 transfers in testnet successfully
Fixes #242
=> VM: Fix block gas limit

pom.xml, src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/ApiVersion.java, src/main/java/org/semux/api/v2/SemuxApiImpl.java, src/main/java/org/semux/api/v2/TypeFactory.java, src/main/java/org/semux/core/Blockchain.java, src/main/java/org/semux/core/BlockchainImpl.java, src/main/java/org/semux/core/TransactionExecutor.java, src/main/java/org/semux/core/TransactionResult.java, src/main/java/org/semux/vm/client/SemuxInternalTransaction.java, src/main/resources/org/semux/api/swagger/v2.4.0.json, src/test/java/org/semux/api/v2/SemuxApiTest.java, src/test/java/org/semux/core/BlockchainImplTest.java, src/test/java/org/semux/core/TransactionResultTest.java
Add internal transaction index to support account-based look-up.
API changes:
- A new property, `internalTransactionCount`, is added to `AccountType`;
- A new endpoint `/account/internal-transactions` is added.
Existing tests and new tests
#249
=> DB: index internal transactions by account

config/semux.properties, src/main/java/org/semux/api/ApiHandler.java, src/main/java/org/semux/api/ApiHandlerImpl.java, src/main/java/org/semux/api/http/HttpHandler.java, src/main/java/org/semux/config/AbstractConfig.java, src/main/java/org/semux/config/Config.java, src/main/resources/org/semux/api/swagger/v2.4.0.json, src/test/java/org/semux/api/http/HttpHandlerTest.java
This PR introduces the concept of public and private services, to partially resolve #271.
Existing unit tests
#271
=> API: enhance the service grouping

config/semux.properties
Looks like semux01 and semux02 are temporarily down, so wallets are not syncing. I'm adding another seed node with few validators @ semux.info
=> Add more Mainnet DNS seed nodes
